### ISSUE TITLE
Tasks for oppfølging etter risikovurdering

### ISSUE THREAD

**Issue by aas-tbuar** [Altinn/kunde#13]
Oppfølgingsoppgaver etter risikovurdering.

Team kunde skal gjennomgå følgende tiltak knyttet til risiko:

```[tasklist]
### Tasks
- [x] R27 R28 Tydelig plassering av ansvar for sikkerhetsrutiner, derunder vulnerability management
- [x] R32 R38 Kreve at tjenesteeier gjør godkjenningstest av egen app
- [ ] R32 Oppretthold en oversikt over frister for tjenester høyvolumperioder
- [x] R32 Kreve at tjenesteeier har en plan for håndtering av tjenesteutilgjengelighet
- [x] R33 Erfaringsoverføring på tvers av tjenesteeiere
- [x] R38 Skriv inn krav om personellsikkerhet i tjenesteeieravtalen
- [ ] R44 Still krav til at tjenesteeier tester APIer
- [x] R60 Opprett en oversikt over kontaktpersoner hos TE til bruk ved hendelseshåndtering.
```

**Comment by aas-tbuar** [comment]
@HanneLauritsen1967 kan du gi meg en tilbakemelding på hvilke av punktene over som dekkes av bilag 3?

**Comment by HanneLauritsen1967** [comment]
Har markert punktene jeg mener er greit nok dekket.

**Comment by aas-tbuar** [comment]
R27 R28 Tydelig plassering av ansvar for sikkerhetsrutiner, derunder vulnerability management
-	Kapabiliteten vulnerability management håndteres av Mottaksprosjektet

R32 R38 Kreve at tjenesteeier gjør godkjenningstest av egen app
-	Krav til test av egne applikasjoner skal ligge hos hver enkelt tjenesteeier og skal ligge som krav/føring i produktspesifikke bruksvilkår.

R32 Oppretthold en oversikt over frister for tjenester høyvolumperioder
-	Oversikt over høyvolkumsperioder er driftskritisk for drift og forvaltning av altinn og vil bli fulgt opp i videre arbeid med ny teknisk brukerstøtte og kundedialog.

R32 Kreve at tjenesteeier har en plan for håndtering av tjenesteutilgjengelighet
-	Denne vil bli håndtert i bruksvilkår.

R33 Erfaringsoverføring på tvers av tjenesteeiere
-	For å få til god erfaringsoverføring, må det bygges opp en kultur for samarbeid og kunnskapsdeling, tilrettelegges for tekniske og organisatoriske verktøy, og legges til rette for strukturerte og uformelle møtepunkter. Dette vil kunne styrke tjenesteutviklingen på Altinn-plattformen, sikre bedre samsvar mellom tjenester, og gjøre det enklere for nye tjenesteeiere å komme i gang. Denne holdes i videre av Kundeteamet.

R38 Skriv inn krav om personellsikkerhet i tjenesteeieravtalen
-	Håndteres av bruksvilkår

R44 Still krav til at tjenesteeier tester APIer
-	Skal dekkes av bruksvilkår mot TE og SSB

R60 Opprett en oversikt over kontaktpersoner hos TE til bruk ved hendelseshåndtering.
-	I Altinn 2 eksisterte en komplet liste med kontaktinfo fra TE. Denne var aldri riktig og skapte en falsk trygghet. Oversikt over kontaktinfo på TE vil erstattes av kontaktpunkt på Slack.
